### ISSUE TITLE
Commune boundaries are now available as open data

### ISSUE THREAD

**Issue by grischard** [dtonhofer/MunicipalitiesOfLuxembourg#1]
Hi,

The commune boundaries are now open data:

https://data.public.lu/en/datasets/limites-administratives-du-grand-duche-de-luxembourg/

The _quartiers_ of Luxembourg and Esch aren't yet though.

**Comment by dtonhofer** [comment]
Thanks Guillaume (more than 2y later : +1). I added a note to the README.
